name: Supabase Backup

on:
  schedule:
    - cron: "0 18 * * *"  # Every day at 6 PM UTC (12 AM BDT)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"  # Ensure the correct Node.js version

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
        run: echo $SUPABASE_ACCESS_TOKEN | supabase login --token

      - name: Create a Database Backup
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          BACKUP_FILE="supabase_backup_$TIMESTAMP.sql"
          supabase db dump --out $BACKUP_FILE

      - name: Upload Backup as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: supabase_backup
          path: supabase_backup_*.sql
